-- 2026-07-team-bios-de.sql
-- The German team bios did not match the approved English bios: several
-- contained fabricated employers (e.g. "Griffin Capital Management", "Lynch
-- Oil Shale Investments", "Dresdner Kleinwort Wasserstein"), an invented
-- Harvard certificate, and wrong years of experience. Replace bio_de with a
-- faithful German translation of each member's English bio (bio_en) — same
-- facts, firms, dates and roles, no additions or omissions.

UPDATE team_members SET bio_de = '<p>Aziz verfügt über mehr als 30 Jahre internationale Erfahrung aus London, Prag und Istanbul als Finanzanalyst, Stratege, Head of Research und Portfoliomanager in den EEMEA-Märkten. Er ist der Gründer von Mori Capital Management. Aziz verwaltet den Mori Ottoman Fund seit dessen Auflegung im Januar 2006; der Fonds wurde mehrfach als bestperformender Regionalfonds in Emerging Europe ausgezeichnet (1. Platz über 10 Jahre von Euro und Euro am Sonntag, u. a. 2016 und 2017). Aziz und der von ihm verwaltete Fonds erhielten zahlreiche Branchenauszeichnungen von Morningstar, Sauren, Euro, Euro am Sonntag, Feri Ratings und Citywire. Er hält einen BA in Betriebswirtschaftslehre der Anglo-American University.</p>' WHERE slug = 'aziz-unan';
UPDATE team_members SET bio_de = '<p>Özlem verfügt über mehr als 25 Jahre Erfahrung an den türkischen Kapitalmärkten als leitende Investmentbanking-Führungskraft. Sie begann ihre Laufbahn bei İŞ Investment Securities Inc., wo sie die institutionellen Sales- und Trading-Teams leitete und leitende Funktionen bei IPOs und SPOs an der Borsa İstanbul innehatte. Von 1999 bis 2001 verwaltete Özlem die in Luxemburg ansässigen SICAV-Fonds der İşbank mit einem verwalteten Vermögen von 450 Mio. USD. 2009 wechselte sie zu Noego Partners Ltd., und 2013 gründete sie gemeinsam mit Aziz die Unan Portföy Yönetimi A.Ş. Sie hält einen BA der Bilkent University.</p>' WHERE slug = 'ozlem-tumer-eke';
UPDATE team_members SET bio_de = '<p>Desmond verfügt über mehr als 25 Jahre Erfahrung in der internationalen Fondsbranche mit fundiertem Hintergrund in Fondsbuchhaltung, Operations und Investment Servicing. Seit 2016 ist er Chief Operations Officer der Mori Capital Management Limited. Zuvor bekleidete Desmond mehrere leitende Positionen in der Fondsbuchhaltung bei BNY Mellon in Irland sowie bei PNC Global Investment Servicing in Irland und Polen, wo er 2008 das polnische Büro des Unternehmens aufbaute. Davor war er als Analyst bei AQR Capital Management und Bear Stearns in New York City tätig, nachdem er seine Laufbahn bei Merrill Lynch in Irland begonnen hatte. Er hält einen Bachelor of Commerce der University College Dublin.</p>' WHERE slug = 'desmond-riordan';
UPDATE team_members SET bio_de = '<p>Isidro verfügt über mehr als 25 Jahre Erfahrung in der Finanzbranche. Zehn Jahre lang war er in verschiedenen Funktionen im Londoner Büro von Bloomberg tätig, unter anderem als Mitglied der Abteilung Portfolio Trading Systems (2006–2010), wo er für die Implementierung von Bloombergs umfassender Portfoliomanagement-Lösung AIM verantwortlich war. Anschließend war er sechs Jahre bei Renaissance Asset Managers im Bereich Performance- und Risikomanagement tätig, bevor er zu Mori Capital Management kam. Isidro hält einen BA der University of Vigo und einen MA der Anglia Ruskin University sowie AMLRO- und Compliance-Qualifikationen.</p>' WHERE slug = 'isidro-garcia-de-la-torre';
UPDATE team_members SET bio_de = '<p>Peter verfügt über umfangreiche internationale Erfahrung in den Bereichen Asset Management, institutionelle Geschäftsentwicklung und Corporate Finance mit einem besonderen Fokus auf den deutschsprachigen Raum Europas. Er kam im April 2016 zu Mori Capital Management und ist in München ansässig. Zuvor leitete er ab 2011 das Geschäft von Renaissance Asset Managers im deutschsprachigen Europa, nachdem er für das institutionelle Geschäft der Janus Capital Group in derselben Region verantwortlich gewesen war und 2009 das Münchener Büro von Janus Capital eröffnet hatte. Davor war er Head of Northern Europe bei Scottish Widows Investment Partnership und war zwölf Jahre im Corporate Finance bei Salomon Brothers, Lehman Brothers, CSFB und UBS tätig. Er hält einen Doktortitel sowie einen MBA der Universität St. Gallen (Dr. oec., lic. oec. HSG, Banking and Finance).</p>' WHERE slug = 'peter-zurhorst';
UPDATE team_members SET bio_de = '<p>Jean-Paul verfügt über mehr als ein Jahrzehnt Erfahrung in den Bereichen Finanzen, Risk Services und Fondsadministration. Er begann seine Laufbahn im Finanzwesen 2012 als Fondsadministrator bei einem führenden maltesischen Fondsadministrator, bevor er 2015 zu RiskCap International Limited wechselte, wo er 2023 zum Head of Risk Services befördert wurde. Zudem ist er nebenberuflich Dozent an der University of Malta in der Abteilung Banking and Finance der FEMA. Jean-Paul hält einen Bachelor of Commerce der University of Malta, einen Master in Investment and Finance der University of Strathclyde sowie einen Master in Risk, Crisis and Resilience Management der University of Portsmouth.</p>' WHERE slug = 'jean-paul-gauci';
